/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class sky_skyndk_MainActivity */

#ifndef _Included_sky_skyndk_MainActivity
#define _Included_sky_skyndk_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     sky_skyndk_MainActivity
 * Method:    getSkyNDKText
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_sky_skyndk_MainActivity_getSkyNDKText
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
